### ISSUE TITLE
Solution for [attribute^=value] Selector

### ISSUE THREAD

**Issue by cedricdelpoux** [css-system/css-system#21]
Hi, 

The following is not working:
```
'&[class^="my-class"]': {
    color: "#fff"
 },
```

Because `.style-xyz[class^="my-class"]` is not a valid css selector.

Is there an other solution instead of:
```
"&.my-class-a, &.my-class-b, &.my-class-c", &.my-class-d": {
    color: "#fff"
 },
```

Thank you

**Comment by myagoo** [comment]
I don't understand what you want to achieve here.
Also, `.style-xyz[class^="my-class"]` **is** a valid selector, it is just not gonna work since the the classname of the element I think you are trying to target certainly begins with a css-system computed classname (depending on how  you pass the computed classname to the underlying dom element).

**Comment by myagoo** [comment]
`.style-xyz[class^="my-class"]` means 

> Please target any node with a class style-xyz, but only if it class attribute begins with my-class

**Comment by myagoo** [comment]
Closing this since the selector is valid AND working in css-system.
The issue you might be encountering must be a selector specificity issue.
